
project_id = "jdbepvxzqqjnkgnojosh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://jdbepvxzqqjnkgnojosh.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[functions.send-contact-email]
verify_jwt = false

[functions.senepay-ai-chat]
verify_jwt = false

[functions.init-knowledge-base]
verify_jwt = false
